baseURL = "https://m2.nz/"
languageCode = "en"
defaultContentLanguage = "en"

title = "m2.nz"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Daniel Mason"
  headline = "Snr Site Reliability Engineer | Pilot"
  image = "img/dp.jpg"  # path relative to static directory

  links = [
    { cv = { href = "/cv", text = "CV", target = "_self" } },
    # { email = "mailto:daniel@m2.nz" },
    # { link = "https://link-to-some-website.com/" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { bandcamp = "https://username.bandcamp.com" },
    # { bluesky = "https://bsky.app/profile/username" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    { linkedin = "https://linkedin.com/in/idanoo" },
    { github = "https://github.com/idanoo" },
    # { gitlab = "https://gitlab.com/idanoo" },
    # { google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://last.fm/user/username" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { spotify = "https://spotify.com/user/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    { steam = "https://steamcommunity.com/id/idanoo" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://threads.com/username" },
    { tiktok = "https://tiktok.com/@idanoo.nz" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { x = "https://x.com/username" },
    # { youtube = "https://youtube.com/username" },
    { quic = { href = "https://account.quic.nz/refer/19099", text = "Quic Broadband" } },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"

[markup.goldmark.renderer]
  unsafe = true