pipeline:
  build:
    image: alpine
    commands:
      - apk update
      - apk add openssh
      - echo $M2_DEPLOY_KEY > privkey
      - chmod 0600 privkey
      - ssh -i privkey -o StrictHostKeyChecking=no root@$M2_HOST 'cd /var/www/m2.nz && git pull && chown www-data:users -R /var/www/m2.nz && sudo systemctl reload nginx.service'
      - rm -fr privkey
    secrets: [ m2_deploy_key, m2_host ]
