baseURL = 'https://m2.nz/'
languageCode = 'en-us'
title = 'Daniel Mason'
theme = "m10c"

[markup.goldmark.renderer]
  unsafe = true
  
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "CV"
    url = "/cv/"
    weight = 3

[params]
  author = "Daniel Mason"
  description = "Personal blog"
  avatar = "profile.png"
  menu_item_separator = " | "
  favicon = "/favicon.ico"

  [[params.social]]
    icon = "git-pull-request"
    name = "GitLab"
    url = "https://git.m2.nz/idanoo"
  [[params.social]]
    icon = "send"
    name = "Mastodon"
    url = "https://mastodon.nz/@idanoo"
  [[params.social]]
    icon = "camera"
    name = "Pixelfed"
    url = "https://pixelfed.nz/idanoo"
  [[params.social]]
    icon = "message-square"
    name = "Matrix"
    url = "https://matrix.to/#/@idanoo:mtrx.nz"

[params.style]
  darkestColor = "#242930"
  darkColor = "#353b43"
  lightColor = "#afbac4"
  lightestColor = "#ffffff"
  primaryColor = "#57cc8a"
