pipeline:
  build:
    image: alpine
    branches: main
    commands:
      - apk update
      - apk add openssh
      - eval $(ssh-agent -s)
      - echo "$M2_DEPLOY_KEY" | tr -d '\r' | ssh-add -
      - ssh -o StrictHostKeyChecking=no root@$M2_HOST 'cd /var/www/m2.nz && git pull && hugo && chown www-data:users -R /var/www/m2.nz && sudo systemctl reload nginx.service'
    secrets: [ m2_deploy_key, m2_host ]
